- name: PLAY1 - SNMP
  hosts: junos-spine
  connection: netconf
  gather_facts: no

  tasks:

    - name: TASK1 in PLAY1
      junos_config:
        lines:
          - set snmp community public authorization read-only
          - set snmp community vdmsvdms authorization read-only
