---
- name: PLAY1 - Create Directories
  hosts: junos-spine
  connection: local
  gather_facts: no

  tasks:

    - file:
        path: ./host_vars/{{ inventory_hostname }}
        state: directory

    - file: 
        path: ./templates
        state: directory

    - file:
        path: ./configs/{{ inventory_hostname }}
        state: directory

    - file:
        path: ./group_vars
        state: directory

- name: PLAY2 - Generate SNMP config
  hosts: junos-spine
  connection: local
  gather_facts: no

  tasks:
    - template:
        src: snmp.j2
        dest: ./configs/{{ inventory_hostname }}/{{ inventory_hostname }}-snmp.conf

